version: '3'
services:
  php:
    image: romeoz/docker-apache-php:5.6
    ports:
      - 9595:80
    depends_on:
      - db
    volumes:
      - ./app/:/var/www/app
  
  db:
    image: mariadb:10.6
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "Root885dm."
      MYSQL_DATABASE: "db_simbada"
      MYSQL_USER: "simbada"
      MYSQL_PASSWORD: "mie4yamb4ks0"
    container_name: mysql

volumes:
  data:
    driver: local